version: "3.8"

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./api:/app  # Optional: for live code reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    env_file:
      - .env
    command: ["python", "main.py"]
